from datetime import datetime

class FeedEvent:
    """
    Domain entity representing a feed event generated by a device.
    Stores the device ID, the timestamp when the feed was dispensed, and the duration.
    """
    def __init__(
            self,
            device_id: str,
            dispensed_at: datetime,
            duration: float,
            id: int = None
    ):
        self.id = id  # Unique identifier for the feed event (optional)
        self.device_id = device_id  # ID of the device that dispensed the feed
        self.dispensed_at = dispensed_at  # Timestamp when the feed was dispensed
        self.duration = duration  # Duration of the feed dispensing in seconds

class PondRecord:
    """
    Domain entity representing a sensor record from a pond monitoring device.
    Stores the device ID, type of record, value, and creation timestamp.
    """
    def __init__(
            self,
            device_id: str,
            temp: float,
            ph: float,
            turbidity: float,
            created_at: datetime,
            id: int = None,
    ):
        self.id = id
        self.device_id = device_id
        self.temp = temp
        self.ph = ph
        self.turbidity = turbidity
        self.created_at = created_at