from datetime import datetime

class FeedEvent:
    """
    Domain entity representing a feed event generated by a device.
    Stores the device ID, the timestamp when the feed was dispensed, and the duration.
    """
    def __init__(
            self,
            device_id: str,
            dispensed_at: datetime,
            duration: float,
            id: int = None
    ):
        self.id = id  # Unique identifier for the feed event (optional)
        self.device_id = device_id  # ID of the device that dispensed the feed
        self.dispensed_at = dispensed_at  # Timestamp when the feed was dispensed
        self.duration = duration  # Duration of the feed dispensing in seconds

class PondRecord:
    """
    Domain entity representing a sensor record from a pond monitoring device.
    Stores the device ID, type of record, value, and creation timestamp.
    """
    def __init__(
            self,
            device_id: str,
            record_type: str,
            value: float,
            created_at: datetime,
            id: int = None
    ):
        self.id = id  # Unique identifier for the sensor record (optional)
        self.device_id = device_id  # ID of the device that sent the record
        self.record_type = record_type  # Type of sensor data (e.g., temperature, turbidity)
        self.value = value  # Value measured by the sensor
        self.created_at = created_at  # Timestamp when the record was created
